spring:
  logging:
    level:
      org:
        springframework:
          r2dbc: TRACE
      reactor.netty.http.client.HttpClient: TRACE
      sun.net.www.protocol.http.HttpURLConnection: TRACE
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: test
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
